### ISSUE TITLE
Non-uppercase environment variables

### ISSUE THREAD

**Issue by ilyash-b** [awslabs/aws-centralized-logging#13]
It's surprising to see non-uppercase environment variables. What I observed in thousands of other scripts from different sources is uppercase with underscores.

https://github.com/awslabs/aws-centralized-logging/blob/0cb0dcd1ecce6e3e0851b271d792dace2b1719e9/source/services/indexing/index.js#L28

**Comment by gsingh04** [comment]
This has been addressed, closing issue.

**Comment by ilyash-b** [comment]
There are search results:

https://github.com/awslabs/aws-centralized-logging/search?q=DomainEndpoint&unscoped_q=DomainEndpoint

Did not dive into it but it seems that at least https://github.com/awslabs/aws-centralized-logging/blob/2a396e4633e07fccafb1937ed7564dca5c2b1120/source/services/indexing/package.json#L31 is relevant
