### ISSUE TITLE
Enhancement suggestion: report which environment variable exactly is not set

### ISSUE THREAD

**Issue by ilyash-b** [awslabs/aws-centralized-logging#14]
https://github.com/awslabs/aws-centralized-logging/blob/0cb0dcd1ecce6e3e0851b271d792dace2b1719e9/source/services/indexing/index.js#L42

**Comment by maykays** [comment]
Please up-vote if you want this feature. Do not submit a new feature request.

**Comment by mobri2a** [comment]
Latest version (3.2) logs the value of each of the environmental variables so it's easy to see which is the issue.
