### ISSUE TITLE
node.js 8.10 soon be deprecated.

### ISSUE THREAD

**Issue by Thulaseeram** [awslabs/aws-centralized-logging#17]
Hi,

Any plans to upgrade the runtime to newer version of node.js 12.x??
thanks,

**Comment by mohsenari** [comment]
Hi @Thulaseeram Thanks for notifying us on the issue. I confirmed that we are working on updating our solutions to node.js 12.x version, including this solution. Please keep an eye on this repository for new releases.

**Comment by georgebearden** [comment]
This issue has been addressed in the latest commit.
