### ISSUE TITLE
cognito email should not be mutable

### ISSUE THREAD

**Issue by jesusch** [awslabs/aws-centralized-logging#18]
https://github.com/awslabs/aws-centralized-logging/blob/master/deployment/centralized-logging-primary.template#L159

should be set to false
I was trying to add Federation with Google. 
As of reading this thread it does not work:
https://github.com/amazon-archives/amazon-cognito-auth-js/issues/48#issuecomment-582375073
Initial 1st login works. When you logout and login again there is not even an error message
Only in web console I found: invalid user attributes: email attribute cannot be updated

**Comment by mobri2a** [comment]
Thanks for the feedback. We'll research this for a future update: _add Cognito integration testing with Google to the solution testing we perform and verify that federation with Google works correctly._

**Comment by AlexeyKhmelev** [comment]
Have the same issue. Customer incident. Terrible...

**Comment by gsingh04** [comment]
Please see here on steps to add social identity provider on AWS Centralized Logging Solution. [Appendix D: Adding social identity providers](https://docs.aws.amazon.com/solutions/latest/centralized-logging/appendix-d.html)

**Comment by gmcgarry** [comment]
> Please see here on steps to add social identity provider on AWS Centralized Logging Solution. [Appendix D: Adding social identity providers](https://docs.aws.amazon.com/solutions/latest/centralized-logging/appendix-d.html)

That page does not address the problem.

**Comment by DavidWells** [comment]
I am also seeing this problem.

Is the solution making the email field mutable on stack creation? (described here https://github.com/amazon-archives/amazon-cognito-auth-js/issues/48#issuecomment-582375073)
