### ISSUE TITLE
Error: "Creating Elasticsearch Domain did not stabilize"

### ISSUE THREAD

**Issue by luizgustavogp** [awslabs/aws-centralized-logging#2]
Hello, this template does not work for me. 

After a long time CloudFormation rollback with this error: "Creating Elasticsearch Domain did not stabilize".

**Error:** 
CREATE_FAILED | AWS::Elasticsearch::Domain | ElasticsearchAWSLogs | Creating Elasticsearch Domain did not stabilize.

After searching about this problem I found a suggestion to modify the Elasticsearch  **AdvancedOptions**

```
"AdvancedOptions": {
					"indices.fielddata.cache.size": "",
					"rest.action.multi.allow_explicit_index": "true"
				}
```

Any idea?

**Comment by luizgustavogp** [comment]
After updated the **AdvancedOption** configuration  to : 

```
"AdvancedOptions": {
					"indices.fielddata.cache.size": 40,
					"rest.action.multi.allow_explicit_index": "true"
				}
```

Works for me.  The `**indices.fielddata.cache.size**`  property can not be empty.

**Comment by gsingh04** [comment]
v2.0 of the solution is now live!
