### ISSUE TITLE
Option to deploy ElasticSearch cluster in VPC

### ISSUE THREAD

**Issue by anujag24** [awslabs/aws-centralized-logging#20]
The default configuration deploys Elastic Search Cluster with public access with no option to choose for deploying it in VPC.

**Comment by mobri2a** [comment]
Good suggestion. We'll add this to the backlog for consideration in a future update. Thanks for the feedback!

**Comment by maykays** [comment]
Please up-vote if you want this feature. Do not submit a new feature request.

**Comment by gsingh04** [comment]
Please see [here](https://docs.aws.amazon.com/solutions/latest/centralized-logging/security.html) for more details on this architecture update in v4.0.0 release.
