### ISSUE TITLE
Use Kinesis Firehose for event ingestion

### ISSUE THREAD

**Issue by kvaibhawa** [awslabs/aws-centralized-logging#21]
Hello,
I am reviewing your stack https://aws.amazon.com/solutions/implementations/centralized-logging/ and also reviewing another solution using Kinesis Firehose. 
Trying to understand the benefits of your solutions vs using kinesis firehose??

Thanks

**Comment by mobri2a** [comment]
Thanks for the question! At the time the solution was written, Amazon Kinesis Firehose was not yet available. We are considering use of Amazon Kinesis in a future release.

**Comment by maykays** [comment]
Please up-vote if you want this feature. Do not submit a new feature request.

**Comment by gsingh04** [comment]
Please see here for the updated [architecture](https://docs.aws.amazon.com/solutions/latest/centralized-logging/architecture.html) for release v4.0.0
