### ISSUE TITLE
Version 4.0 not available

### ISSUE THREAD

**Issue by Vikasjx** [awslabs/aws-centralized-logging#24]
**Describe the bug**

It seems version 4.0 of Centralized logging is not available. When I am trying to deploy the solution, version 3.2 template is getting deployed

**To Reproduce**

try to deploy this template in your environment...its deploying version 3.2 only

**Expected behavior**

Version 4.0 should be deployed

**Please complete the following information about the solution:**

- [x] Version: 4.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0134) - The AWS CloudFormation template for deployment of the AWS Centralized WAF & SG Management. Version **v1.0.0**_". You can also find the version from [releases](https://github.com/awslabs/aws-centralized-logging/releases)

- [x] Region: eu-west-1, us-east-1
- [x] Was the solution modified from the version published on this repository? no, I am doing a fresh deployment
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? yes, Quota is all fine
- [x] Were there any errors in the CloudWatch Logs? [How to enable debug mode?] nope, by Default version 3.2 is getting deployed

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by gsingh04** [comment]
We apologize for the inconvenience. We are working to get the documentation fixed for the latest release. You are correct it is pointing to old links. For latest release please use following links:
[Solution Primary Template](https://solutions-reference.s3.amazonaws.com/centralized-logging/latest/aws-centralized-logging.template)
[Solution Demo Template](https://solutions-reference.s3.amazonaws.com/centralized-logging/latest/aws-centralized-logging-demo.template)

**Comment by gsingh04** [comment]
The documentation and the relevant links have been updated.
https://docs.aws.amazon.com/solutions/latest/centralized-logging/welcome.html

**Comment by Vikasjx** [comment]
There seems to be another issue now. While trying to configure subscription filter in spoke account. It is unable to parse CL-Destination.

**An error occurred (InvalidParameterException) when calling the PutSubscriptionFilter operation: 1 validation error detected: Unable to parse destinationArn 'arn:aws:logs:eu-west-1:97645xxxxxxx:destination:CL-Destination'**

command I am running in spoke account:
**aws logs put-subscription-filter --destination-arn 'arn:aws:logs:eu-west-1:97645xxxxxxx:destination:CL-Destination' --log-group-name aws-cloudtrail-logs-57009xxxxxxx-a8a419f7 --filter-name Prod_Cloudtrail_FILTER --filter-pattern "" --region eu-west-1**

**Comment by Vikasjx** [comment]
Thanks, issue is resolved now
