### ISSUE TITLE
Please add feature to deploy solution in Customer's VPC

### ISSUE THREAD

**Issue by Vikasjx** [awslabs/aws-centralized-logging#25]
**Is your feature request related to a problem? Please describe.**
CLM creates its own VPC at present. There should be an option to deploy in customer's VPC

**Describe the feature you'd like**
Add option to deploy CLM solution in customer's VPC

**Additional context**

**Comment by gsingh04** [comment]
Thanks @Vikasjx for submitting the feature request. 

We purposely create a separate VPC for the Kinesis and Elasticsearch resources. This VPC is configured with needed isolated and public subnets, with the appropriate route table rules and appropriate minimal security group rules. You would notice, that the VPC has been designed and configured keeping in mind all the security best practices and allows **only** the least permissive rules. If we use a customer VPC, it would be difficult to ensure the VPC meets the needed configurations.

**Comment by Vikasjx** [comment]
Thanks @gsingh04 for your response but how about Jump host. Customer's have to open port 3389 on public internet to access Jump host. If solution can be deployed in customer's own VPC then jump host would not be needed and Kibana Dashboard can be accessed from Customer's VPC. Is there any secure way to access Kibana Dashboard without provisioning a Jump Host?

**Comment by gsingh04** [comment]
@Vikasjx have you tried VPC peering connection. I haven't tested this at my end, and it would be great if you can let us know how it goes. You should be able to peer your VPC with the VPC created by the solution and access Kibana from your VPC.
[VPC Peering](https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html)
You would also need to update the security group rule on the Elasticsearch domain to allow inbound traffic from your VPC.

**Comment by Vikasjx** [comment]
Yes, it works with VPC peering but the challenge is that this solution deploys a very broad VPC with CIDR 10.0.0.0/16 which mostly overlaps with customer's VPC as this range is widely used by many customers. This solution blocks 65536 IPs for an ES cluster and Kinesis firehose. Think these can be easily deployed in customer's own VPC if script is written to do so

**Comment by gsingh04** [comment]
You can change CIDR block here as desired. https://github.com/awslabs/aws-centralized-logging/blob/a44dcfe5ac8f32e991e85a637a02dcabd7a68b80/source/resources/lib/manifest.json#L14

This is why we exposed CIDR block in manifest file so you can easily tweak it if needed. 

For customizing the deployment, follow steps [here](https://github.com/awslabs/aws-centralized-logging#customization).

**Comment by Vikasjx** [comment]
ok, this is good...will explore this option
