### ISSUE TITLE
Demo templae fails to install

### ISSUE THREAD

**Issue by onahum2018** [awslabs/aws-centralized-logging#26]
**Describe the bug**

When installing the main template and selecting 'Yes' to install the Demo logs, the installation fails and CF is performing a rollback, same happens when the demo template is installed independently.
when selecting 'No' foe the demo logs, everything works as expected. 
**To Reproduce**

Install the template and select "yes' to instal the demo logs

CF error event:

Embedded stack arn:aws:cloudformation:us-east-1:654081729127:stack/rf-imd-cl-CLDemoStackNestedStackCLDemoStackNestedStackResource3DB21482-1KIQV4D19FXLP/796c94b0-7991-11eb-84fd-0ad959ac0b5f was not successfully created: The following resource(s) failed to create: [DemoVPC2409DB3F, WebServerDemoEC2InstanceRoleF681DFE4, demoTrailLogsRole36F2CC79, CloudTrailSubscription, flowRole5E4EF2F1, WebServerWebServerSubscription7595409C, FlowLogSubscription, DemoVPCIGWD7695CC8, TrailBucketA831CE63].

- [ ] Version: AWS CloudFormation template for deployment of the centralized-logging. Version v4.0.0

- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? no issues
- [ ] Were there any errors in the CloudWatch Logs? No
- [ ] (https://docs.aws.amazon.com/solutions/latest/centralized-logging/appendix-d.html)

**Comment by gsingh04** [comment]
Hello,

Thanks for your question.

**Issue:** If you notice the events in failed nested stack you should see similar error: *User with accountId: xxxxxx is not authorized to perform: logs:PutSubscriptionFilter on resource*

**Reasoning:** 
Spoke Accounts | <Requires input> | A comma delimited list of account IDs for log indexing. Enter the primary account ID along with any secondary account ID. Post-deployment, you can add or remove accounts by updating this parameter
-- | -- | --

*Enter the primary account ID along with any secondary account ID.* You must provide the primary account id.

**Resolution:** You can update the primary stack **Spoke Account** parameter, provide primary account-id where you deployed the stack and then chose to deploy sample logs.

**Reference:** Check *Error in creating a CloudWatch Logs subscription filter* in troubleshooting section
https://docs.aws.amazon.com/solutions/latest/centralized-logging/appendix-e.html
