### ISSUE TITLE
NPM instal fails with Node 14.15.5

### ISSUE THREAD

**Issue by stowns** [awslabs/aws-centralized-logging#31]
Docs have `Prerequisite: Node.js>10` but install build fails with `14.15.5`

**To Reproduce**
```
me@a483e79e80c9 aws-centralized-logging % nodenv shell 14.15.5
me@a483e79e80c9 aws-centralized-logging % npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: aws-centralized-logging@4.0.0
npm ERR! Found: typescript@4.2.4
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"^4.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"3.9.x || 4.0.x" from typedoc@0.19.2
npm ERR! node_modules/typedoc
npm ERR!   dev typedoc@"^0.19.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Expected behavior**

npm installation is successful 

**Please complete the following information about the solution:**

- [x] Version: 4.0.0
- [x] Region: all
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? [How to enable debug mode?](https://docs.aws.amazon.com/solutions/latest/centralized-logging/appendix-d.html) No

**Comment by gsingh04** [comment]
This has been addressed with release v4.0.1
