### ISSUE TITLE
Where I can find the cl-transformer.zip?

### ISSUE THREAD

**Issue by alexKoltman** [awslabs/aws-centralized-logging#35]
Hi, 

I took a look on your implementation of: 

https://github.com/awslabs/aws-centralized-logging/blob/master/source/resources/lib/cl-primary-stack.ts 

here you are using a lambda-transformer with: 

code: Code.fromAsset(
        "../../source/services/transformer/dist/cl-transformer.zip"
), 
      
Where can I find this zip? 
When I downloaded the project, I was not able to find it out. 

Thanks

**Comment by gsingh04** [comment]
Hello,

Here is the source code: https://github.com/awslabs/aws-centralized-logging/tree/master/source/services/transformer

**Comment by alexKoltman** [comment]
Thanks. :)
