### ISSUE TITLE
update existing cloudwatch loggroup

### ISSUE THREAD

**Issue by sbonasu** [awslabs/aws-centralized-logging#7]
Hi, I was able to create ES domain, cognito user pool and lambdas(SolutionHelper, LambdaESCognito, LogStreamer) with the help of primary template and zip files.

We have lot of existing CW log groups that need to be streamed to LogStreamer lambda

Do I have to write my own script to update existing and new CW log groups stream to LogStreamer lambda? Does Amazon provide any helper script that works well with centralized logging solution.

Thank you

**Comment by gsingh04** [comment]
thanks for your question. that is something you would have to do and the steps are outlined [here](https://docs.aws.amazon.com/solutions/latest/centralized-logging/appendix-b.html)

**Comment by sbonasu** [comment]
ok, thank you. Since we have more than 400 existing log groups, I wrote a script to update them
