### ISSUE TITLE
spoke account stream lambda not able to resolve master elasticsearch dns endpoint

### ISSUE THREAD

**Issue by sbonasu** [awslabs/aws-centralized-logging#8]
below errors are showing up in stream lambda(spoke account) logs.. 
I masked the endpoint address here. 
Please let me help troubleshoot the issue(I can open support ticket if that is the best route)

2019-01-03T15:21:17.047Z	36cca839-0f6b-11e9-a920-f532e7454853
{
    "errorMessage": "getaddrinfo ENOTFOUND https://search-testcentralizedlogging-xxxxxxxxxxxxx.us-east-2.es.amazonaws.com https://search-testcentralizedlogging-xxxxxxxxxxxxx.us-east-2.es.amazonaws.com:443",
    "errorType": "Error",
    "stackTrace": [
        "errnoException (dns.js:50:10)",
        "GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)"
    ]
}

2019-01-03T15:21:17.047Z	36cca839-0f6b-11e9-a920-f532e7454853	[ERROR]postElasticSearchBulkData Error:
{
    "code": "ENOTFOUND",
    "errno": "ENOTFOUND",
    "syscall": "getaddrinfo",
    "hostname": "https://search-testcentralizedlogging-xxxxxxxxxxxxx.us-east-2.es.amazonaws.com",
    "host": "https://search-testcentralizedlogging-xxxxxxxxxxxxx.us-east-2.es.amazonaws.com",
    "port": 443
}

**Comment by gsingh04** [comment]
please see troubleshooting section on our solution guide [Amazon ES Bulk Data Error](https://docs.aws.amazon.com/solutions/latest/centralized-logging/appendix-d.html)

**resolution:** For Elasticsearch Endpoint, verify that you entered the correct endpoint. Make sure that the endpoint does not include https://. Then, select Next.

**Comment by sbonasu** [comment]
thank you
