### ISSUE TITLE
Integration with nginx logs

### ISSUE THREAD

**Issue by pedro380085** [awslabs/aws-centralized-logging#9]
Great tutorial, in which I would like to add a follow up question: how can we visualize nginx logs on my recently created centralized logging solution?

I do understand that we must install a copy `logstash`, is there a tutorial on how to do so?

**Comment by gsingh04** [comment]
Currently the solution integrates only with Amazon CloudWatch Logs. In your case where you want nginx logs to be indexed on Amazon Elasticsearch using the solution, you would need to leverage CloudWatch agent to push the nginx logs to CloudWatch. Once you have the logs there, you could follow [these](https://docs.aws.amazon.com/solutions/latest/centralized-logging/appendix-b.html) instructions to index them on ES.
You should also check [demo](https://docs.aws.amazon.com/solutions/latest/centralized-logging/appendix-a.html) mode of the solution, where we index sample apache logs from EC2 on ES using similar mechanism as stated above.

**Comment by maykays** [comment]
Please up-vote if you want this feature. Do not submit a new feature request.
